---
apiVersion: v1
kind: Namespace
metadata:
  name: xmrig
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmrig
  namespace: xmrig
  labels:
    app: xmrig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xmrig
  template:
    metadata:
      labels:
        app: xmrig
    spec:
      containers:
        - name: xmrig
          image: aakhtar3/xmrig
          env:
            - name: URL
              value: 'pool.hashvault.pro:443'
            - name: WALLET
              value: abc
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: '2'
            limits:
              cpu: '4'
